"""initial schema

Revision ID: 26a5446780e6
Revises: 
Create Date: 2026-04-05 23:59:40.173886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a5446780e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('equity', 'mutual_fund', 'crypto', 'forex', name='assettype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_symbol'), 'asset', ['symbol'], unique=False)
    op.create_table('daily_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.Enum('morning', 'evening', name='reporttype'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('prediction_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('llm_narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_report_report_date'), 'daily_report', ['report_date'], unique=False)
    op.create_index('ix_report_date_type', 'daily_report', ['report_date', 'report_type'], unique=False)
    op.create_table('paper_wallet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('invested_balance', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('peak_equity', sa.Float(), nullable=False),
    sa.Column('monthly_topup', sa.Float(), nullable=False),
    sa.Column('risk_mode', sa.Enum('normal', 'conservative', 'halted', name='riskmode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('buy', 'sell', 'hold', name='signalaction'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rl_score', sa.Float(), nullable=False),
    sa.Column('transformer_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('ensemble_score', sa.Float(), nullable=False),
    sa.Column('market_regime', sa.String(), nullable=False),
    sa.Column('technical_indicators', sa.JSON(), nullable=False),
    sa.Column('sentiment_sources', sa.JSON(), nullable=False),
    sa.Column('is_intraday', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_asset_created', 'signal', ['asset_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_signal_created_at'), 'signal', ['created_at'], unique=False)
    op.create_table('wallet_transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('topup', 'trade_open', 'trade_close', 'adjustment', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['paper_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_outcome',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_direction', sa.String(), nullable=False),
    sa.Column('predicted_delta_pct', sa.Float(), nullable=False),
    sa.Column('actual_delta_pct', sa.Float(), nullable=True),
    sa.Column('outcome', sa.Enum('correct', 'wrong', 'pending', name='outcomeresult'), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['daily_report.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('buy', 'sell', name='tradeaction'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'stopped', 'expired', name='tradestatus'), nullable=False),
    sa.Column('trade_type', sa.Enum('intraday', 'positional', name='tradetype'), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('intraday_capital_used', sa.Float(), nullable=True),
    sa.Column('positional_capital_used', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_entry_time'), 'trade', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trade_status'), 'trade', ['status'], unique=False)
    op.create_index('ix_trade_status_type', 'trade', ['status', 'trade_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_status_type', table_name='trade')
    op.drop_index(op.f('ix_trade_status'), table_name='trade')
    op.drop_index(op.f('ix_trade_entry_time'), table_name='trade')
    op.drop_table('trade')
    op.drop_table('prediction_outcome')
    op.drop_table('wallet_transaction')
    op.drop_index(op.f('ix_signal_created_at'), table_name='signal')
    op.drop_index('ix_signal_asset_created', table_name='signal')
    op.drop_table('signal')
    op.drop_table('paper_wallet')
    op.drop_index('ix_report_date_type', table_name='daily_report')
    op.drop_index(op.f('ix_daily_report_report_date'), table_name='daily_report')
    op.drop_table('daily_report')
    op.drop_index(op.f('ix_asset_symbol'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
