"""add notes to paper_wallet

Revision ID: a6fa19d4d7de
Revises: 26a5446780e6
Create Date: 2026-05-04 21:45:55.225227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fa19d4d7de'
down_revision: Union[str, Sequence[str], None] = '26a5446780e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_wallet', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_wallet', 'notes')
    # ### end Alembic commands ###
