"""add_signal_outcome_table

Revision ID: c3469cff5ee1
Revises: a6fa19d4d7de
Create Date: 2026-05-12 17:50:09.234844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3469cff5ee1'
down_revision: Union[str, Sequence[str], None] = 'a6fa19d4d7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signal_outcome', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('signal_outcome', 'signal_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('signal_outcome', 'trade_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('signal_outcome', 'outcome',
               existing_type=sa.VARCHAR(),
               server_default=None,
               type_=sa.Enum('correct', 'wrong', 'pending', name='outcomeresult'),
               existing_nullable=False)
    op.alter_column('signal_outcome', 'opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signal_outcome', 'opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('signal_outcome', 'outcome',
               existing_type=sa.Enum('correct', 'wrong', 'pending', name='outcomeresult'),
               server_default=sa.text("'pending'::character varying"),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('signal_outcome', 'trade_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('signal_outcome', 'signal_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('signal_outcome', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
